### ISSUE TITLE
Crash on server 1.6 [1.18.1]

### ISSUE THREAD

**Issue by red2blue** [Wurst-Imperium/Mo-Glass#23]
Crash on server start up

[01:50:41] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'mo_glass'!
        at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.5) ~[?:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.12.11.jar:?]
        at net.minecraft.server.Main.main(Main:106) [server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602) [fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.11.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.11.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_1921
        at net.wurstclient.glass.MoGlassBlocks.initialize(MoGlassBlocks.java:149) ~[Mo-Glass-1.6-MC1.18.1.jar:?]
        at net.wurstclient.glass.MoGlass.initialize(MoGlass.java:22) ~[Mo-Glass-1.6-MC1.18.1.jar:?]
        at net.wurstclient.glass.MoGlassInitializer.onInitializeServer(MoGlassInitializer.java:36) ~[Mo-Glass-1.6-MC1.18.1.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.11.jar:?]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1921
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.12.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.wurstclient.glass.MoGlassBlocks.initialize(MoGlassBlocks.java:149) ~[Mo-Glass-1.6-MC1.18.1.jar:?]
        at net.wurstclient.glass.MoGlass.initialize(MoGlass.java:22) ~[Mo-Glass-1.6-MC1.18.1.jar:?]
        at net.wurstclient.glass.MoGlassInitializer.onInitializeServer(MoGlassInitializer.java:36) ~[Mo-Glass-1.6-MC1.18.1.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.11.jar:?]
        ... 15 more

**Comment by Alexander01998** [comment]
Fixed in v1.6.1.
